### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [kcarullo/intro-data-capstone-biodiversity#5]
(Exceeds Expectations)

Well done on this project! Good job on all the calculations as well as data visualizations. In addition, your presentation slides were very thorough and efficient in presenting your findings. I liked how you gave an overview of the presentation at the start and then went into detail on each section. 

As a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by kcarullo** [comment]
Thank you for the review.
